accessible_charts: true
accessible_tabs: true
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    #- path: /news
    #  label: menu.updates
contrast_type: default
cookie_consent_form:
  enabled: false
country:
  name: indicator.ciudad
  adjective: indicator.ciudad
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: true
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /
    layout: frontpage
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: http://prose.io/#ODSValencia2/data/edit/develop/data/indicator_[id].csv
data_fields:
  units: ''
  series: ''
decimal_separator: ','
date_formats: 
  - type: standard
    language: en
    format: '%B %d, %Y'
  - type: standard
    language: es
    format: '%d de %B de %Y'
  - type: standard
    language: ca
    format: '%d de %B de %Y'
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
favicons: favicon.io
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/EstadisticaVLC'
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: frontpage.info
    content: |
    
      [Web Oficina d'Estadística de l'Ajuntament de València](https://www.valencia.es/cas/estadistica/ods_principal)
    #content: ''
    #include: ''
    #button_label: frontpage.enlace_ods
    #button_link: 'https://www.valencia.es/cas/estadistica/ods_principal'
    #rule_color: ''
frontpage_goals_grid:
  title: frontpage.title
  description: frontpage.instructions
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: https://github.com/ODSValencia2/data/tree/develop/indicator-config/[id]
  translation_link: https://github.com/ODSValencia2/data/tree/develop/translations/[language]/[group].yml
indicator_data_form:
  enabled: true
  repository_link: https://github.com/ODSValencia2/data/tree/develop/data/[id]
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: https://github.com/ODSValencia2/data/tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: true
languages:
  - ca
  - es
languages_public: []
logos: []
map_layers:
  -
    # The subfolder under 'geojson' in the data repository holding the GeoJSON files:
    subfolder: regions
    # The label to use in the "Download GeoJSON" button:
    label: Distritos
    # The minimum zoom at which this layer should be visible.
    min_zoom: 0
    # The maximum zoom at which this layer should be visible.
    max_zoom: 20
    # Whether or not these boundaries should display statically on lower layers.
    staticBorders: true
map_options:
  minZoom: 5
  maxZoom: 20
  tileURL: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  tileOptions:
  #  id: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  #  accessToken: ''
    attribution:  <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>
  #colorRange: chroma.brewer.BuGn
  colorRange: [["#FCE9EB", "#F7BDC4", "#F2929D", "#ED6676", "#E83A4F", "#E5243B", "#B71D2F", "#891623", "#5C0E18", "#2E070C"],
               ["#FCF8EB", "#F7E9C2", "#F2DB9A", "#EDCD72", "#E8BE49", "#E5B735", "#CEA530", "#A08025", "#735C1B", "#453710"],
               ["#EDF5EB", "#C9E2C3", "#A6CF9C", "#82BC74", "#5EA94C", "#4C9F38", "#3D7F2D", "#2E5F22", "#1E4016", "#0F200B"],
               ["#F9E8EA", "#EEBAC0", "#E28C96", "#D65E6C", "#CB3042", "#C5192D", "#9E1424", "#760F1B", "#4F0A12", "#270509"],
               ["#FFEBE9", "#FFC4BC", "#FF9D90", "#FF7564", "#FF4E37", "#FF3A21", "#CC2E1A", "#992314", "#66170D", "#330C07"],
               ["#E9F8FB", "#BEEBF6", "#93DEF0", "#67D1EA", "#3CC4E5", "#26BDE2", "#1E97B5", "#177188", "#0F4C5A", "#08262D"],
               ["#FFF9E7", "#FEEDB6", "#FEE185", "#FDD554", "#FCC923", "#FCC30B", "#CA9C09", "#977507", "#654E04", "#322702"],
               ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"],
               ["#FFF0E9", "#FED2BE", "#FEB492", "#FE9666", "#FD783B", "#FD6925", "#CA541E", "#983F16", "#652A0F", "#331507"],
               ["#FCE7F0", "#F5B8D1", "#EE89B3", "#E75A95", "#E02B76", "#DD1367", "#B10F52", "#850B3E", "#580829", "#2C0415"],
               ["#FFF5E6", "#FEE2B3", "#FECE80", "#FEBA4D", "#FDA71A", "#FD9D00", "#CA7E00", "#985E00", "#653F00", "#331F00"],
               ["#FAF5EA", "#EFE0C0", "#E4CC96", "#D9B86C", "#CEA342", "#C9992D", "#A17A24", "#795C1B", "#503D12", "#281F09"],
               ["#ECF2EC", "#C5D8C7", "#9FBFA2", "#79A57C", "#528B57", "#3F7E44", "#326536", "#264C29", "#19321B", "#0D190E"],
               ["#E7F5FB", "#B6E0F4", "#85CBEC", "#54B6E4", "#23A1DD", "#0A97D9", "#0879AE", "#065B82", "#043C57", "#021E2B"],
               ["#EEF9EA", "#CCECBF", "#ABE095", "#89D36B", "#67C640", "#56C02B", "#459A22", "#34731A", "#224D11", "#112609"],
               ["#E6F0F5", "#B3D2E2", "#80B4CE", "#4D95BA", "#1A77A7", "#00689D", "#00537E", "#003E5E", "#002A3F", "#00151F"],
               ["#E8EDF0", "#BAC8D2", "#8CA4B5", "#5E7F97", "#305A79", "#19486A", "#143A55", "#0F2B40", "#0A1D2A", "#050E15"]]
  #noValueColor: '#f0f0f0'
  #styleNormal:
  #  weight: 1
  #  opacity: 1
  #  fillOpacity: 0.7
  #  color: '#888888'
  #  dashArray: ''
  #styleHighlighted:
  #  weight: 1
  #  opacity: 1
  #  fillOpacity: 0.7
  #  color: '#111111'
  #  dashArray: ''
  #styleStatic:
  #  weight: 2
  #  opacity: 1
  #  fillOpacity: 0
  #  color: '#172d44'
  #  dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
metadata_edit_url: http://prose.io/#ODSValencia2/data/edit/develop/meta/[id].yml
metadata_tabs:
  - scope: national
    title: custom-translations.local-metadata
    description: custom-translations.description-local-metadata
news:
  category_links: false
non_global_metadata: indicator.local_metadata
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://odsvalencia2.github.io/data/'
reporting_status:
  title: status.reporting_status
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported
      hide_on_goal_pages: false
    - value: inprogress
      label: status.statistics_in_progress
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/ODSValencia2/data'
repository_url_site: 'https://github.com/ODSValencia2/site'
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: https://github.com/ODSValencia2/sdg-translations2/tree/develop/translations/[language]/[group].yml
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
